"Zero",
"Sycos",#Displacement
"Sysin",#Transparency
"Lambda",
"BACK","BACK","BACK","BACK","BACK","BACK",
"X","Y","Z","Occ","Biso","B11","B22","B33","B12","B13","B23",
"X","Y","Z","Occ","Biso","B11","B22","B33","B12","B13","B23",
"X","Y","Z","Occ","Biso","B11","B22","B33","B12","B13","B23",
"Scale","Shape1",
"Bov",#Overall B-factor
"Str1","Str2","Str3",
"U","V","W","X","Y",
"GausSiz",#1G
"LorSiz",#SZ
"a","b","c","alpha","beta","gamma",
"Pref1","Pref2",#G
"PA1","PA2","PA3","PA4",#Asym
"S_L","D_L",
#
Zero-Pattern[0]
Sycos-Pattern[0]
Sysin-Pattern[0]
Lambda-Pattern[0]
BACK-Background
BACK-Background
BACK-Background
BACK-Background
BACK-Background
BACK-Background
X-Atom[0]
Y-Atom[0]
Z-Atom[0]
Occ-Atom[0]
Biso-AtomicDisplacementFactor
B11-AtomicDisplacementFactor
B22-AtomicDisplacementFactor
B33-AtomicDisplacementFactor
B12-AtomicDisplacementFactor
B13-AtomicDisplacementFactor
B23-AtomicDisplacementFactor
X-Atom[1]
Y-Atom[1]
Z-Atom[1]
Occ-Atom[1]
Biso-AtomicDisplacementFactor
B11-AtomicDisplacementFactor
B22-AtomicDisplacementFactor
B33-AtomicDisplacementFactor
B12-AtomicDisplacementFactor
B13-AtomicDisplacementFactor
B23-AtomicDisplacementFactor
X-Atom[2]
Y-Atom[2]
Z-Atom[2]
Occ-Atom[2]
Biso-AtomicDisplacementFactor
B11-AtomicDisplacementFactor
B22-AtomicDisplacementFactor
B33-AtomicDisplacementFactor
B12-AtomicDisplacementFactor
B13-AtomicDisplacementFactor
B23-AtomicDisplacementFactor
Scale-Contribution[0]
Shape1-Profile
Bov-Contribution[0]
Str1-StrainParameter
Str2-StrainParameter
Str3-StrainParameter
U-Profile
V-Profile
W-Profile
X-Profile
Y-Profile
GausSiz-Profile
LorSiz-Profile
a-Phase[0]
b-Phase[0]
c-Phase[0]
alpha-Phase[0]
beta-Phase[0]
gamma-Phase[0]
Pref1-PreferOrient
Pref2-PreferOrient
PA1-AsymmetryParameter
PA2-AsymmetryParameter
PA3-AsymmetryParameter
PA4-AsymmetryParameter
S_L-AsymmetryParameter
D_L-AsymmetryParameter
