# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui.ui'
#
# Created: Sat Jul 26 18:29:23 2025
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1062, 523)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/xp/.designer/backup/AutoFP.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet(_fromUtf8(""))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(-10, 0, 1061, 911))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.params_widget = QtGui.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(16)
        self.params_widget.setFont(font)
        self.params_widget.setAutoFillBackground(False)
        self.params_widget.setStyleSheet(_fromUtf8(""))
        self.params_widget.setObjectName(_fromUtf8("params_widget"))
        self.tabWidgettable = QtGui.QTabWidget(self.params_widget)
        self.tabWidgettable.setGeometry(QtCore.QRect(10, 10, 471, 461))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidgettable.setFont(font)
        self.tabWidgettable.setObjectName(_fromUtf8("tabWidgettable"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidgetprofile = QtGui.QTableWidget(self.tab)
        self.tableWidgetprofile.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidgetprofile.setFont(font)
        self.tableWidgetprofile.setStyleSheet(_fromUtf8(""))
        self.tableWidgetprofile.setRowCount(0)
        self.tableWidgetprofile.setColumnCount(4)
        self.tableWidgetprofile.setObjectName(_fromUtf8("tableWidgetprofile"))
        self.tabWidgettable.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableWidgetins = QtGui.QTableWidget(self.tab_4)
        self.tableWidgetins.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidgetins.setFont(font)
        self.tableWidgetins.setRowCount(0)
        self.tableWidgetins.setColumnCount(4)
        self.tableWidgetins.setObjectName(_fromUtf8("tableWidgetins"))
        self.tabWidgettable.addTab(self.tab_4, _fromUtf8(""))
        self.Atom = QtGui.QWidget()
        self.Atom.setObjectName(_fromUtf8("Atom"))
        self.tableWidgetatom = QtGui.QTableWidget(self.Atom)
        self.tableWidgetatom.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetatom.setFont(font)
        self.tableWidgetatom.setStatusTip(_fromUtf8(""))
        self.tableWidgetatom.setColumnCount(4)
        self.tableWidgetatom.setObjectName(_fromUtf8("tableWidgetatom"))
        self.tableWidgetatom.setRowCount(0)
        self.tabWidgettable.addTab(self.Atom, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tableWidgetatombiso = QtGui.QTableWidget(self.tab_6)
        self.tableWidgetatombiso.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidgetatombiso.setFont(font)
        self.tableWidgetatombiso.setColumnCount(4)
        self.tableWidgetatombiso.setObjectName(_fromUtf8("tableWidgetatombiso"))
        self.tableWidgetatombiso.setRowCount(0)
        self.tabWidgettable.addTab(self.tab_6, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidgetother = QtGui.QTableWidget(self.tab_5)
        self.tableWidgetother.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidgetother.setFont(font)
        self.tableWidgetother.setRowCount(0)
        self.tableWidgetother.setColumnCount(4)
        self.tableWidgetother.setObjectName(_fromUtf8("tableWidgetother"))
        self.tabWidgettable.addTab(self.tab_5, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tableWidgetocc = QtGui.QTableWidget(self.tab_8)
        self.tableWidgetocc.setGeometry(QtCore.QRect(0, 0, 471, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetocc.setFont(font)
        self.tableWidgetocc.setStatusTip(_fromUtf8(""))
        self.tableWidgetocc.setColumnCount(4)
        self.tableWidgetocc.setObjectName(_fromUtf8("tableWidgetocc"))
        self.tableWidgetocc.setRowCount(0)
        self.tabWidgettable.addTab(self.tab_8, _fromUtf8(""))
        self.buttonrefineall = QtGui.QPushButton(self.params_widget)
        self.buttonrefineall.setGeometry(QtCore.QRect(10, 498, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif SC"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonrefineall.setFont(font)
        self.buttonrefineall.setObjectName(_fromUtf8("buttonrefineall"))
        self.buttonclearall = QtGui.QPushButton(self.params_widget)
        self.buttonclearall.setGeometry(QtCore.QRect(100, 498, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif SC"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonclearall.setFont(font)
        self.buttonclearall.setObjectName(_fromUtf8("buttonclearall"))
        self.button_params_ok = QtGui.QPushButton(self.params_widget)
        self.button_params_ok.setGeometry(QtCore.QRect(405, 498, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(10)
        self.button_params_ok.setFont(font)
        self.button_params_ok.setObjectName(_fromUtf8("button_params_ok"))
        self.widget_3 = QtGui.QWidget(self.params_widget)
        self.widget_3.setGeometry(QtCore.QRect(368, 0, 120, 31))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.spinbox_phase = QtGui.QSpinBox(self.widget_3)
        self.spinbox_phase.setGeometry(QtCore.QRect(68, 13, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(12)
        self.spinbox_phase.setFont(font)
        self.spinbox_phase.setObjectName(_fromUtf8("spinbox_phase"))
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(20, 15, 50, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setAcceptDrops(True)
        self.widget.setStyleSheet(_fromUtf8(""))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.tabwidget_run = QtGui.QTabWidget(self.widget)
        self.tabwidget_run.setEnabled(True)
        self.tabwidget_run.setGeometry(QtCore.QRect(100, 10, 431, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabwidget_run.setFont(font)
        self.tabwidget_run.setStyleSheet(_fromUtf8(""))
        self.tabwidget_run.setDocumentMode(False)
        self.tabwidget_run.setObjectName(_fromUtf8("tabwidget_run"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.Buttonautorun = QtGui.QPushButton(self.tab_3)
        self.Buttonautorun.setGeometry(QtCore.QRect(120, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Buttonautorun.setFont(font)
        self.Buttonautorun.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Buttonautorun.setObjectName(_fromUtf8("Buttonautorun"))
        self.buttonautoselect = QtGui.QPushButton(self.tab_3)
        self.buttonautoselect.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonautoselect.setFont(font)
        self.buttonautoselect.setObjectName(_fromUtf8("buttonautoselect"))
        self.buttonorder = QtGui.QPushButton(self.tab_3)
        self.buttonorder.setGeometry(QtCore.QRect(220, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonorder.setFont(font)
        self.buttonorder.setObjectName(_fromUtf8("buttonorder"))
        self.spinBox = QtGui.QSpinBox(self.tab_3)
        self.spinBox.setGeometry(QtCore.QRect(380, 20, 42, 22))
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(100)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(330, 20, 54, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabwidget_run.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.buttonback = QtGui.QPushButton(self.tab_2)
        self.buttonback.setGeometry(QtCore.QRect(150, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.buttonback.setFont(font)
        self.buttonback.setObjectName(_fromUtf8("buttonback"))
        self.buttonrun = QtGui.QPushButton(self.tab_2)
        self.buttonrun.setGeometry(QtCore.QRect(10, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.buttonrun.setFont(font)
        self.buttonrun.setObjectName(_fromUtf8("buttonrun"))
        self.tabwidget_run.addTab(self.tab_2, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.pushButton_prf2origin = QtGui.QPushButton(self.tab_9)
        self.pushButton_prf2origin.setGeometry(QtCore.QRect(20, 15, 130, 30))
        self.pushButton_prf2origin.setObjectName(_fromUtf8("pushButton_prf2origin"))
        self.pushButton_makpcr = QtGui.QPushButton(self.tab_9)
        self.pushButton_makpcr.setGeometry(QtCore.QRect(180, 15, 130, 30))
        self.pushButton_makpcr.setStyleSheet(_fromUtf8(""))
        self.pushButton_makpcr.setObjectName(_fromUtf8("pushButton_makpcr"))
        self.tabwidget_run.addTab(self.tab_9, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_7)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 501, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabwidget_run.addTab(self.tab_7, _fromUtf8(""))
        self.texteditshow = QtGui.QTextEdit(self.widget)
        self.texteditshow.setGeometry(QtCore.QRect(20, 132, 511, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.texteditshow.setFont(font)
        self.texteditshow.setStyleSheet(_fromUtf8("color: rgb(14, 6, 255);"))
        self.texteditshow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.texteditshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.texteditshow.setReadOnly(True)
        self.texteditshow.setObjectName(_fromUtf8("texteditshow"))
        self.buttonfold = QtGui.QPushButton(self.widget)
        self.buttonfold.setGeometry(QtCore.QRect(20, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        self.buttonfold.setFont(font)
        self.buttonfold.setStyleSheet(_fromUtf8(""))
        self.buttonfold.setObjectName(_fromUtf8("buttonfold"))
        self.text_path = QtGui.QLineEdit(self.widget)
        self.text_path.setGeometry(QtCore.QRect(20, 105, 511, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC Medium"))
        self.text_path.setFont(font)
        self.text_path.setStyleSheet(_fromUtf8(""))
        self.text_path.setFrame(False)
        self.text_path.setReadOnly(True)
        self.text_path.setObjectName(_fromUtf8("text_path"))
        self.check_show_rwp = QtGui.QCheckBox(self.widget)
        self.check_show_rwp.setGeometry(QtCore.QRect(80, 480, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        self.check_show_rwp.setFont(font)
        self.check_show_rwp.setCheckable(True)
        self.check_show_rwp.setChecked(True)
        self.check_show_rwp.setObjectName(_fromUtf8("check_show_rwp"))
        self.check_show_fp = QtGui.QCheckBox(self.widget)
        self.check_show_fp.setGeometry(QtCore.QRect(250, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        self.check_show_fp.setFont(font)
        self.check_show_fp.setChecked(True)
        self.check_show_fp.setObjectName(_fromUtf8("check_show_fp"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-10, 0, 120, 101))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.buttonopen = QtGui.QPushButton(self.widget_2)
        self.buttonopen.setGeometry(QtCore.QRect(30, 10, 70, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.buttonopen.setFont(font)
        self.buttonopen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonopen.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.buttonopen.setObjectName(_fromUtf8("buttonopen"))
        self.progress = QtGui.QProgressBar(self.widget)
        self.progress.setGeometry(QtCore.QRect(250, 500, 260, 22))
        self.progress.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.progress.setStyleSheet(_fromUtf8(""))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName(_fromUtf8("progress"))
        self.labelpar = QtGui.QLabel(self.widget)
        self.labelpar.setGeometry(QtCore.QRect(60, 502, 191, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        self.labelpar.setFont(font)
        self.labelpar.setText(_fromUtf8(""))
        self.labelpar.setObjectName(_fromUtf8("labelpar"))
        self.button_stop = QtGui.QToolButton(self.widget)
        self.button_stop.setGeometry(QtCore.QRect(477, 500, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans SC"))
        self.button_stop.setFont(font)
        self.button_stop.setStyleSheet(_fromUtf8(""))
        self.button_stop.setObjectName(_fromUtf8("button_stop"))
        self.buttonoutput = QtGui.QPushButton(Form)
        self.buttonoutput.setEnabled(False)
        self.buttonoutput.setGeometry(QtCore.QRect(1060, 430, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonoutput.setFont(font)
        self.buttonoutput.setObjectName(_fromUtf8("buttonoutput"))
        self.textrwp = QtGui.QTextEdit(Form)
        self.textrwp.setGeometry(QtCore.QRect(1070, 500, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ADMUI3Lg"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textrwp.setFont(font)
        self.textrwp.setStyleSheet(_fromUtf8("color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));"))
        self.textrwp.setObjectName(_fromUtf8("textrwp"))

        self.retranslateUi(Form)
        self.tabWidgettable.setCurrentIndex(0)
        self.tabwidget_run.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "AutoFP", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.tab), _translate("Form", "profile", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.tab_4), _translate("Form", "instrument", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.Atom), _translate("Form", "Atom", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.tab_6), _translate("Form", "Atom_biso", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.tab_5), _translate("Form", "other", None))
        self.tabWidgettable.setTabText(self.tabWidgettable.indexOf(self.tab_8), _translate("Form", "Occ", None))
        self.buttonrefineall.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" color:#ff00ff;\">Select all parameters of this page</span></p></body></html>", None))
        self.buttonrefineall.setText(_translate("Form", "refine all", None))
        self.buttonclearall.setText(_translate("Form", "clear all", None))
        self.button_params_ok.setText(_translate("Form", "OK", None))
        self.spinbox_phase.setToolTip(_translate("Form", "<html><head/><body><p>Phase</p></body></html>", None))
        self.label_2.setText(_translate("Form", " phase:", None))
        self.Buttonautorun.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000;\">start auto-refinement !</span></p></body></html>", None))
        self.Buttonautorun.setText(_translate("Form", "Run", None))
        self.buttonautoselect.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">autoselect the parameters to refine </span></p></body></html>", None))
        self.buttonautoselect.setWhatsThis(_translate("Form", "<html><head/><body><p>auto select parameter</p></body></html>", None))
        self.buttonautoselect.setText(_translate("Form", "AutoSelect", None))
        self.buttonorder.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">setting of AutoFP</span></p></body></html>", None))
        self.buttonorder.setText(_translate("Form", "Setting", None))
        self.spinBox.setToolTip(_translate("Form", "<html><head/><body><pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:10pt; color:#000000;\">&quot;cycle=0&quot; represent auto-select the cycles number;</span></pre><pre style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:10pt; color:#000000;\">&quot;cycle=n&gt;0&quot; represent run n cycles.</span></pre></body></html>", None))
        self.label.setText(_translate("Form", "Cycle:", None))
        self.tabwidget_run.setTabText(self.tabwidget_run.indexOf(self.tab_3), _translate("Form", "Auto", None))
        self.buttonback.setText(_translate("Form", "back", None))
        self.buttonrun.setText(_translate("Form", "run", None))
        self.tabwidget_run.setTabText(self.tabwidget_run.indexOf(self.tab_2), _translate("Form", "Manual", None))
        self.pushButton_prf2origin.setText(_translate("Form", "Prf -> Origin", None))
        self.pushButton_makpcr.setText(_translate("Form", "Makepcr", None))
        self.tabwidget_run.setTabText(self.tabwidget_run.indexOf(self.tab_9), _translate("Form", "Tool", None))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans SC\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">AutoFP</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Website: <a href=\"http://physiworld.vipsinaapp.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://physiworld.vipsinaapp.com/</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Authors: Xiaopeng Cui ...o Jincang Zhang </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Institute: Shanghai University</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">--------------------------------------------------</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current version : 1.3.x</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Feedback Email : autofp@163.com</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LICENSE: GPL v3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All copyright reversed 2014-2025</p></body></html>", None))
        self.tabwidget_run.setTabText(self.tabwidget_run.indexOf(self.tab_7), _translate("Form", "About", None))
        self.buttonfold.setText(_translate("Form", ">", None))
        self.check_show_rwp.setText(_translate("Form", "Show Rwp curve", None))
        self.check_show_fp.setText(_translate("Form", "Show FP out", None))
        self.buttonopen.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff00ff;\">Open *.pcr file</span></p></body></html>", None))
        self.buttonopen.setText(_translate("Form", "Open", None))
        self.button_stop.setToolTip(_translate("Form", "<html><head/><body><p>stop the auto-refinement!</p></body></html>", None))
        self.button_stop.setText(_translate("Form", "stop", None))
        self.buttonoutput.setText(_translate("Form", "output", None))

